# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Nagios-Plugin-Beanstalk
version:      0.02
version_from: lib/Nagios/Plugin/Beanstalk.pm
installdirs:  site
requires:
    Beanstalk::Client:             0
    Nagios::Plugin:                0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
